package mp3onlinepro.trungpt.com.mp3onlinepro.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import mp3onlinepro.trungpt.com.mp3onlinepro.db.FavoriteSong;

import mp3onlinepro.trungpt.com.mp3onlinepro.db.FavoriteSongDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig favoriteSongDaoConfig;

    private final FavoriteSongDao favoriteSongDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favoriteSongDaoConfig = daoConfigMap.get(FavoriteSongDao.class).clone();
        favoriteSongDaoConfig.initIdentityScope(type);

        favoriteSongDao = new FavoriteSongDao(favoriteSongDaoConfig, this);

        registerDao(FavoriteSong.class, favoriteSongDao);
    }
    
    public void clear() {
        favoriteSongDaoConfig.getIdentityScope().clear();
    }

    public FavoriteSongDao getFavoriteSongDao() {
        return favoriteSongDao;
    }

}
