package com.cntt.freemusicdownloadnow.db;

import com.cntt.freemusicdownloadnow.ui.model.Song;
import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "FAVORITE_SONG".
 */
@Entity
public class FavoriteSong {

    @Id
    private Long id;
    private String title;
    private String urlSource;
    private String urlThumbnail;
    private String urlDownload;
    private String artist;
    private Long duration;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 1771750319)
    public FavoriteSong() {
    }

    public FavoriteSong(Long id) {
        this.id = id;
    }

    @Generated(hash = 226544458)
    public FavoriteSong(Long id, String title, String urlSource, String urlThumbnail, String urlDownload, String artist, Long duration) {
        this.id = id;
        this.title = title;
        this.urlSource = urlSource;
        this.urlThumbnail = urlThumbnail;
        this.urlDownload = urlDownload;
        this.artist = artist;
        this.duration = duration;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUrlSource() {
        return urlSource;
    }

    public void setUrlSource(String urlSource) {
        this.urlSource = urlSource;
    }

    public String getUrlThumbnail() {
        return urlThumbnail;
    }

    public void setUrlThumbnail(String urlThumbnail) {
        this.urlThumbnail = urlThumbnail;
    }

    public String getUrlDownload() {
        return urlDownload;
    }

    public void setUrlDownload(String urlDownload) {
        this.urlDownload = urlDownload;
    }

    public String getArtist() {
        return artist;
    }

    public void setArtist(String artist) {
        this.artist = artist;
    }

    public Long getDuration() {
        return duration;
    }

    public void setDuration(Long duration) {
        this.duration = duration;
    }

    // KEEP METHODS - put your custom methods here
    public static FavoriteSong convertFromSong(Song song)
    {
        FavoriteSong favoriteSong = new FavoriteSong();
        favoriteSong.setId(song.getId());
        favoriteSong.setTitle(song.getTitle());
        favoriteSong.setUrlSource(song.getUrlSource());
        favoriteSong.setUrlThumbnail(song.getUrlThumbnail());
        favoriteSong.setUrlDownload(song.getUrlDownload());
        favoriteSong.setArtist(song.getArtist());
        favoriteSong.setDuration(song.getDuration());
        return favoriteSong;
    }
    // KEEP METHODS END

}
